name: tests&linter
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: ls -la
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env: 
          CC_TEST_REPORTER_ID: 6e0c476d530712ac9261c27854e8660e926f7b83f5df1d4c89a9dc183657e951
        with:
          coverageCommand: make test-coverage
          debug: true